#!/usr/bin/env python3
"""
Test script for table_generator.py
"""

import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from table_generator import generate_table_image
from datetime import datetime

def test_table_generation():
    """Test the table generation with sample data"""

    # Sample VWAP scanner data
    sample_data = """
================================================================================
BYBIT FUTURES VWAP SCANNER
================================================================================
Session: ASIAN | Weight: 0.8
================================================================================
RANK SYMBOL         SIGNAL          SCORE   PRICE   VWAP    VOLUME  RSI     MACD    STOCH
================================================================================
1    BTCUSDT        STRONG BUY      95.2    45000   44500   1250000 65.4    0.002   78.5
2    ETHUSDT        BUY             87.8    2800    2750    890000  58.2    0.001   72.1
3    ADAUSDT        STRONG SELL     12.4    0.45    0.48    450000  32.1    -0.001  25.8
4    SOLUSDT        SELL            23.6    95.2    98.5    320000  41.7    -0.002  31.2
5    DOTUSDT        BUY             76.9    8.45    8.20    180000  55.8    0.0005  68.9
================================================================================
"""

    print("Testing table generation...")

    try:
        # Generate the table image
        image_buffer = generate_table_image(
            table_data=sample_data,
            session_name="ASIAN",
            weight="0.8",
            last_updated=datetime.now().strftime("%H:%M:%S"),
            footer_text="Generated by Crypto VWAP Bot"
        )

        # Save to file
        output_path = "test_table_output.png"
        with open(output_path, 'wb') as f:
            f.write(image_buffer.getvalue())

        print(f"✅ Table generation successful!")
        print(f"📁 Image saved to: {output_path}")
        print(f"📊 Image size: {len(image_buffer.getvalue())} bytes")

        return True

    except Exception as e:
        print(f"❌ Table generation failed: {e}")
        import traceback
        traceback.print_exc()
        return False

if __name__ == "__main__":
    success = test_table_generation()
    sys.exit(0 if success else 1)